### ISSUE TITLE
Incorporate custom scripts into schema

### ISSUE THREAD

**Issue by dfornika** [dfornika/pipeline-provenance-schema#2]
We often use custom scripts as part of our overall pipeline. They're distinct from 'tools' like assemblers and aligners. They're generally bundled in the `bin` directory for a nextflow pipeline, and they aren't versioned independently of the overall pipeline.

Proposed schema:

```
scripts:
  - script_name: <filename_of_script>
    interpreter_name: python
    interpreter_version: <python_version>
    libraries:
      - library_name: pandas
        library_version: 2.3.1
    parameters:
      - parameter: <some_parameter>
        value: <some_value>
```
