### ISSUE TITLE
Incorporate databases into schema

### ISSUE THREAD

**Issue by dfornika** [dfornika/pipeline-provenance-schema#3]
We often use databases (blast, kraken, mash, mob-suite, etc.) as part of our analysis, but we don't have a way to describe them in the current schema.

Proposed schema:
```
databases:
  - database_name: <database_name>
    database_version: <database_version>
    files:
      - filename: <filename>
        sha256: <sha256_checksum>
```
